site_name: Langdrive
theme: readthedocs
site_url: https://addy-ai.com/products/langdrive
nav:
  - Home: index.md 
  - Getting Started: gettingStarted.md
  - Yaml: yaml.md 
  - CLI: cli.md  
  - Demo: demo.md 
  - Contributors: contributors.md 
  - Security:
      - security/authentication.md
      - security/verification.md
  - Data Connectors: 
      - Overview: api/dataOverview.md 
      - DriveUtils: api/gdrive.md
      - Email: api/email.md
      - Firestore: api/firestore.md 
  - LLM Services:
      - Overview: api/llmOverview.md
      - HuggingFace: api/huggingFace.md
      - Train: api/train.md  
      - Heroku: api/heroku.md   
      - Chatbot: api/chatbot.md 
